# Generated by Django 5.1.1 on 2024-10-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='time',
            field=models.IntegerField(),
        ),
    ]
