# Generated by Django 5.1.1 on 2024-10-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0002_alter_duration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='al_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='c_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='time',
            field=models.IntegerField(unique=True),
        ),
    ]
