# Generated by Django 5.1.1 on 2024-12-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_alter_algorithm_al_name_alter_coin_c_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duration',
            name='time',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
