# Generated by Django 5.1.1 on 2024-12-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0004_alter_duration_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='duration',
            name='id',
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='al_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='c_name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='time',
            field=models.CharField(max_length=3, primary_key=True, serialize=False, unique=True),
        ),
    ]
