# Generated by Django 5.1.1 on 2024-12-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0005_remove_algorithm_id_remove_coin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='coin',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='duration',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='al_name',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='c_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='duration',
            name='time',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
