# Generated by Django 5.1.1 on 2024-10-06 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositWithdraw_Transaction',
        ),
    ]
