# Generated by Django 4.2.14 on 2024-08-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0002_alter_chart_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
